FROM alpine:3.13

RUN apk add bash make gcc g++ git wget erlang-dev erlang-dialyzer elixir=1.11.2-r0 nodejs=14.16.0-r0 postgresql-client=13.2-r0 inotify-tools=3.20.11.0-r0 npm=14.16.0-r0

RUN mix local.hex --force

RUN mix archive.install hex phx_new 1.5.8 --force

WORKDIR /var/www/html

COPY ./src_code ./var/www/html

EXPOSE 4000 3000 3035 9000 3001
